language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "0.8"
  - "0.6"
script:
  - ./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec -s 6500 -t 8000
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < coverage/lcov.info
